import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import { getSectionContent } from '../services/api';
import { InlineMath, BlockMath } from 'react-katex';
import 'katex/dist/katex.min.css';
import '../styles/SectionContent.css';
import ReactMarkdown from 'react-markdown';
import rehypeKatex from 'rehype-katex';
import remarkMath from 'remark-math';

/**
 * SectionContentPage - Display rich learning content generated by Claude
 *
 * Fetches premium-quality content from backend API
 * Caches content for instant subsequent loads
 */
const SectionContentPage = () => {
  const { topicSlug, weekNumber, sectionId } = useParams();
  const navigate = useNavigate();
  const location = useLocation();

  const topicName = location.state?.topicName || topicSlug.replace(/-/g, ' ');
  const sectionData = location.state?.sectionData || {};

  const [content, setContent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [completed, setCompleted] = useState(false);
  const [showNotes, setShowNotes] = useState(false);
  const [notes, setNotes] = useState('');

  // Load completion status and notes from localStorage
  useEffect(() => {
    const completionKey = `${topicSlug}-${weekNumber}-${sectionId}-completed`;
    const isCompleted = localStorage.getItem(completionKey) === 'true';
    setCompleted(isCompleted);

    const notesKey = `${topicSlug}-${weekNumber}-${sectionId}-notes`;
    const savedNotes = localStorage.getItem(notesKey) || '';
    setNotes(savedNotes);
  }, [topicSlug, weekNumber, sectionId]);

  // Fetch section content from API
  useEffect(() => {
    const fetchContent = async () => {
      try {
        setLoading(true);
        setError(null);

        const sectionTitle = sectionData.title || `Section ${sectionId}`;
        const keywords = sectionData.topics || [];

        const result = await getSectionContent(
          topicName,
          sectionId,
          sectionTitle,
          keywords
        );

        setContent(result);
      } catch (err) {
        console.error('Error fetching section content:', err);
        setError(err.message || 'Failed to load content');
      } finally {
        setLoading(false);
      }
    };

    fetchContent();
  }, [topicName, sectionId, sectionData]);

  const handleCompleteSection = () => {
    const newCompleted = !completed;
    setCompleted(newCompleted);

    const completionKey = `${topicSlug}-${weekNumber}-${sectionId}-completed`;
    localStorage.setItem(completionKey, newCompleted.toString());
  };

  const handleSaveNotes = () => {
    const notesKey = `${topicSlug}-${weekNumber}-${sectionId}-notes`;
    localStorage.setItem(notesKey, notes);
    alert('✓ Notes saved!');
  };

  if (loading) {
    return (
      <div className="section-content-page">
        <div className="loading-container">
          <div className="spinner"></div>
          <p>Loading premium content...</p>
          <p className="loading-hint">Generated with Claude Sonnet 3.5 for maximum quality</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="section-content-page">
        <div className="error-container">
          <h2>⚠️ Error Loading Content</h2>
          <p>{error}</p>
          <button onClick={() => navigate(-1)} className="btn-back">
            ← Back to Topic
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="section-content-page">
      {/* Header */}
      <header className="content-header">
        <button onClick={() => navigate(-1)} className="btn-back">
          ← Back to {topicName}
        </button>
        <div className="header-meta">
          {content?.cached && (
            <span className="cache-badge">⚡ Cached (Instant Load)</span>
          )}
          {content?.generation_model && (
            <span className="model-badge">
              {content.generation_model.includes('claude') ? '🤖 Claude Sonnet 3.5' : '🤖 GPT-4'}
            </span>
          )}
        </div>
      </header>

      {/* Section Title */}
      <div className="section-title-block">
        <h1>
          {sectionData.title || `Section ${sectionId}`}
        </h1>
        <div className="section-meta">
          <span className="time-estimate">
            ⏱️ ~{content?.estimated_minutes || 45} minutes
          </span>
          <button
            className={`btn-complete ${completed ? 'completed' : ''}`}
            onClick={handleCompleteSection}
          >
            {completed ? '✓ Completed' : 'Mark Complete'}
          </button>
        </div>
      </div>

      {/* Main Content - Rendered Markdown with LaTeX */}
      <div className="content-body">
        <ReactMarkdown
          remarkPlugins={[remarkMath]}
          rehypePlugins={[rehypeKatex]}
          components={{
            code({node, inline, className, children, ...props}) {
              return inline ? (
                <code className={className} {...props}>
                  {children}
                </code>
              ) : (
                <pre className="code-block">
                  <code className={className} {...props}>
                    {children}
                  </code>
                </pre>
              );
            }
          }}
        >
          {content?.content || ''}
        </ReactMarkdown>
      </div>

      {/* Notes Section */}
      <div className="notes-section">
        <button
          className="toggle-notes-btn"
          onClick={() => setShowNotes(!showNotes)}
        >
          {showNotes ? '▼' : '▶'} Personal Notes
        </button>

        {showNotes && (
          <div className="notes-container">
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Write your notes here... (saved locally)"
              rows={8}
            />
            <button onClick={handleSaveNotes} className="btn-save-notes">
              💾 Save Notes
            </button>
          </div>
        )}
      </div>

      {/* Footer Actions */}
      <footer className="content-footer">
        <button onClick={() => navigate(-1)} className="btn-secondary">
          ← Back to Topic
        </button>
        <button onClick={handleCompleteSection} className="btn-primary">
          {completed ? 'Mark Incomplete' : '✓ Complete Section'}
        </button>
      </footer>
    </div>
  );
};

export default SectionContentPage;
